server:
  port: 0 # 랜덤하게 지정

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka  
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
spring:
  config:
    import: optional:configserver:http://13.124.204.48:8081
  application:
    name: chat-service
  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
      password : ${REDIS.PASSWD}
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01},${KAFKA_CLUSTER02},${KAFKA_CLUSTER03}
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
