spring:
  config:
    import: optional:configserver:http://13.124.204.48:8081
  application:
    name: chat-service
  profiles:
    active: dev

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

        